### ISSUE TITLE
Remote CLI Usage Request

### ISSUE THREAD

**Issue by elimi98** [Lioness100/free-duolingo-plus#1]
# Referral Code/Link
https://invite.duolingo.com/BDHTZTB5CWWKTDYZAN5O75KGSI
I wouldn't like to go through the installation process,help me please

**Comment by Lioness100** [comment]
![image](https://user-images.githubusercontent.com/65814829/189539058-8efad5f7-ef19-4dc8-8778-8d8d3104bdb6.png)

I ran the command on your behalf. Please let me know if it worked!

**Comment by elimi98** [comment]
Yes worked😀😀😀
Thank you 😊
