### ISSUE TITLE
Remote CLI Usage Request

### ISSUE THREAD

**Issue by elimi98** [Lioness100/free-duolingo-plus#2]
# Referral Code/Link

I wouldn't like to go through the installation process,help me please, it’s referral of my girl 

https://invite.duolingo.com/BDHTZTB5CWWKTXEBSSNF67DO6M

**Comment by Lioness100** [comment]
Done 🙂 
![image](https://user-images.githubusercontent.com/65814829/191120557-7500f414-d1ed-4706-aa33-392ecd98026f.png)

**Comment by elimi98** [comment]
Thanks 🙏
