### ISSUE TITLE
It's not working, can you help me with it.

### ISSUE THREAD

**Issue by ZhangDaJing** [Lioness100/free-duolingo-plus#4]
I used to run the command below on the VPS, but it didn't work, and the Doulingo on my phone didn't receive the free membership.

In this case, do I need to run a VPN? I wonder where the problem is. Is there anything else that needs to be configured?

Thank you for your help.

> [root@VM-0-15-centos ~]# free-duolingo-plus --code https://invite.duolingo.com/BDHTZTB5CWWKSZECNSWQMSNDRI --num 24
> All accounts created! Enjoy your 24 weeks of free Duolingo Plus.
> https://www.duolingo.com/
> [root@VM-0-15-centos ~]#

**Comment by Lioness100** [comment]
Hi! Do you have a school duolingo account? If so, this unfortunately will not work.

**Comment by ZhangDaJing** [comment]
No, this is a new account, and did not apply for the 14-day free trial.

**Comment by Lioness100** [comment]
Discussed on Discord
